### ISSUE TITLE
Prepare alpha release

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2-reverse#62]
**DONE**
- [x] NuGet packages
- [x]  Release notes, + reverse coverage report
- [x] CSOM support table on definition / properties - Improve regression tests - add reverse property suport report #9

**TODO**
- [ ] API usage
- [ ] Docs at docs web site
- [x] Clean up readme file, make a list of supported defs with a link to detailed view
